# Generated by Django 5.1.7 on 2025-03-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('sold', 'Sold')], max_length=15),
        ),
    ]
