# Generated by Django 5.1.7 on 2025-03-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uy', '0002_alter_schedule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
